# TCL File Generated by Component Editor on: 
# Fri Jul 20 22:03:06 CST 2007
# DO NOT MODIFY

set_source_file "avalon_vjtag_master.v"
set_module "avalon_vjtag_master"
set_module_description ""
set_module_property instantiateInSystemModule true
set_module_property version "1.0"
set_module_property group "Avalon Modules"
set_module_property editable true

# Module parameters
add_parameter "data_width" "integer" "32" ""
add_parameter "addr_width" "integer" "32" ""
add_parameter "jtag_instance_index" "integer" "0" ""

# Clock Interface mj_clock
add_clock_interface "mj_clock" 
set_interface_property "mj_clock" "externallyDriven" "false"
set_interface_property "mj_clock" "clockRateKnown" "false"
set_interface_property "mj_clock" "clockRate" "0"
# Ports in interface mj_clock
add_port_to_interface "mj_clock" "avm_mj_clk" "clk"
add_port_to_interface "mj_clock" "avm_mj_reset" "reset"

# Interface mj
add_interface "mj" "avalon" "master" "mj_clock"
set_interface_property "mj" "interleaveBursts" "false"
set_interface_property "mj" "burstOnBurstBoundariesOnly" "false"
set_interface_property "mj" "doStreamReads" "false"
set_interface_property "mj" "isBigEndian" "false"
set_interface_property "mj" "isWriteable" "false"
set_interface_property "mj" "isAsynchronous" "false"
set_interface_property "mj" "registerOutgoingSignals" "false"
set_interface_property "mj" "maxAddressWidth" "32"
set_interface_property "mj" "registerIncomingSignals" "false"
set_interface_property "mj" "dBSBigEndian" "false"
set_interface_property "mj" "alwaysBurstMaxBurst" "false"
set_interface_property "mj" "linewrapBursts" "false"
set_interface_property "mj" "addressGroup" "0"
set_interface_property "mj" "doStreamWrites" "false"
set_interface_property "mj" "isReadable" "false"
# Ports in interface mj
add_port_to_interface "mj" "avm_mj_waitrequest" "waitrequest"
add_port_to_interface "mj" "avm_mj_address" "address"
add_port_to_interface "mj" "avm_mj_read" "read"
add_port_to_interface "mj" "avm_mj_write" "write"
add_port_to_interface "mj" "avm_mj_writedata" "writedata"
add_port_to_interface "mj" "avm_mj_readdata" "readdata"
add_port_to_interface "mj" "avm_mj_resetrequest" "resetrequest"

# IRQ Interface mj_irq
add_interface "mj_irq" "interrupt" "receiver" "mj_clock"
set_interface_property "mj_irq" "irqScheme" "NONE"
set_interface_property "mj_irq" "associatedAddressablePoint" "mj"
# Ports in interface mj_irq
add_port_to_interface "mj_irq" "avm_mj_irq" "irq"
